ets-berkeley-edu/diablo

config/xena.py
tox.ini
xena/__init__.py
xena/conftest.py
xena/test_utils/util.py
xena/test_weapons/test_chakram.py

* Create `config/xena-local.py` to override configs in `config/xena.py`.
* `xena/test_weapons/test_chakram.py` is a reference impl to get us started. We will rename or remove it. 
cc: @pfarestveit

NOJIRA, Xena tests get Flask app init and dedicated configs

---

config/default.py
config/test.py
diablo/__init__.py
diablo/jobs/scheduler.py
requirements.txt
tests/test_jobs/mock_jobs.py
tests/test_jobs/test_scheduler.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-102
See:
* https://schedule.readthedocs.io/en/stable/
* From FAQ of docs above: https://schedule.readthedocs.io/en/stable/faq.html#how-to-continuously-run-the-scheduler-without-blocking-the-main-thread

DIABLO-102, simple, configurable background-jobs thread to run Kaltura integration, etc.

---

config/default.py
config/test.py
diablo/__init__.py
diablo/externals/salesforce.py
diablo/jobs/background_job_manager.py
diablo/jobs/base_job.py
diablo/jobs/course_data_mover.py
diablo/jobs/sample_jobs.py
src/components/CourseDetailsDialog.vue
tests/test_jobs/test_background_job_manager.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-102
I've learned that `app.context` is thread local so you can not access it from another thread. In the job-runner thread, jobs were unable to get at app.configs and logging. This PR fixes.

DIABLO-102, background_job_manager passes app_context to job-runner thread

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-58
Permission to grab diablo-config from S3 when provisioning new EB instance.

DIABLO-58, grant access to private S3 bucket (diablo-deploy-configs)

---

diablo/jobs/kaltura_job.py
diablo/models/scheduled.py
package-lock.json
package.json
scripts/db/schema.sql
src/App.vue
src/views/Approve.vue
src/views/Ouija.vue
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-105
And:
* The `scheduled` table gets two new columns: `publish_type` and `recording_type`. Those values should always match the latest approval.
* For courses with recordings scheduled, the info is nicely displayed on `/approve` page.

DIABLO-105, kaltura_job fix: If admin approval then schedule recordings

---

src/components/course/CoursesDataTable.vue
src/views/room/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-199
Forgot to undo experimental `v-model="undefined"`. 
This PR also fixes jerky-on-sort /rooms page.

DIABLO-199, v-model fix on CoursesDataTable; cleaner /rooms

---

diablo/sql_templates/update_rds_sis_sections.template.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-222
This changes seem to solve the column type related errors I was getting. The latest error: "Non-superusers must provide a password in the connection string" which I do not think requires additional code change. Opinions welcome.

DIABLO-222, specify columns in INSERT of dblink::rds_dblink_to_redshift transaction

---

config/default.py
diablo/lib/db.py
diablo/sql_templates/update_rds_sis_sections.template.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-222
I had to `ALTER COLUMN created_at SET DEFAULT now()` – I could not get `now()` to work in the sql_template query.  I might give diablo's sis_sections table a slight refactor and drop the created_at column in the process. It seems superfluous.

DIABLO-222, diablo dblink to sis_schema, not intermediate schema

---

config/default.py
config/development.py
diablo/api/course_controller.py
src/api/course.ts
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-104
Reverts a portion of PR #135. The goal: allow synchronous call to Kaltura API when course has necessary approvals. It's useful when working on Kaltura integration (localhost only) but otherwise unnecessary.

DIABLO-104, feature_flag to schedule recordings synchronously (intended for local only)

---

diablo/__init__.py
diablo/api/course_controller.py
diablo/externals/kaltura.py
diablo/jobs/util.py
diablo/models/scheduled.py
scripts/db/migrate/2020/20200512-DIABLO-103/add_column_kaltura_schedule_id.sql
scripts/db/schema.sql
src/views/Course.vue
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-103
https://jira.ets.berkeley.edu/jira/browse/DIABLO-282
And, if course has recordings scheduled then admin-user gets a link to Kaltura from `/course` page.

DIABLO-103 / DIABLO-282, store kaltura_schedule_id from API response in 'scheduled' table; delete Kaltura series when click 'Unschedule'

---

diablo/jobs/instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-306
Noticed this bug when documenting email-related logic.

DIABLO-306, use 'continue', not 'next'

---

diablo/api/job_controller.py
diablo/factory.py
diablo/jobs/admin_emails_job.py
diablo/jobs/background_job_manager.py
diablo/jobs/base_job.py
diablo/jobs/canvas_job.py
diablo/jobs/doomed_to_failure.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/kaltura_job.py
diablo/jobs/queued_emails_job.py
diablo/jobs/sis_data_refresh_job.py
diablo/models/development_db.py
tests/test_api/test_course_controller.py
tests/test_api/test_job_controller.py
tests/test_jobs/test_background_job_manager.py
tests/test_jobs/test_canvas_job.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_instructor_emails_job.py
tests/test_jobs/test_kaltura_job.py
tests/test_jobs/test_queued_emails_job.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-251
Singleton in `background_job_manager` instead of hard-to-read `threading.Event` for managing restarts.

DIABLO-251, proper background_job_manager.restart when job settings change; auto_start=True for tests

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-333
Change Diablo's Apache conf to be consistent with Nessie (and with Diablo's own AMI config).
The theory: in a classic example of managerial overreach, having ten WSGI processes is initializing ten separate BackgroundJobManagers, leaving them all to fight over an inadequate pool of labor.

DIABLO-333 Many threads, only one daemon process

---

config/default.py
diablo/api/config_controller.py
diablo/api/room_controller.py
diablo/externals/kaltura.py
diablo/models/approval.py
diablo/models/room.py
scripts/db/migrate/2020/20200526-DIABLO-317/alter_publish_types_enum.sql
scripts/db/schema.sql
src/api/room.ts
src/views/Course.vue
tests/test_api/test_course_controller.py
tests/test_api/test_room_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-317
Updating enum is a must because it was wrongly organized:  'canvas' and 'kaltura_media_gallery' are not separate and distinct options – they are synonymous.

DIABLO-317, alter publish_type enum; /course page text; map schedule to canvas if proper publish_type

---

xena/conftest.py

In `standalone` mode, we skip (1) register_routes and (2) register_jobs.

NOJIRA, Xena app_context init simplified with standalone=True

---

.ebextensions/03_download_local_configuration.config
config/default.py
config/test.py
diablo/api/config_controller.py
diablo/lib/development_db_utils.py
diablo/models/development_db.py
diablo/models/sis_section.py
fixtures/sis/course_capture_pilot.json
fixtures/sis/courses.json
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-380
After mock-course-data has been loaded, we will disable the SisImport job. If we add/remove courses in the file in S3 then we can reload by (1) run SisImport job and (2) hit `/api/start_course_capture_pilot` endpoint.

DIABLO-380, /api/start_course_capture_pilot loads pilot courses JSON (pulled from S3, like config)

---

diablo/jobs/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-393
This bug impacted courses with multiple instructors.

DIABLO-393, avoid dupe section_ids in cross_listed_section_ids table

---

.ebextensions/00_ami.config

Reverts PR #257 
Unclear why env vars are not picked up. I'll review logs.

DIABLO-399, revert changes to 00_ami.config

---

.ebextensions/00_ami.config

I want to give this another try. Let's start with `aws:autoscaling:launchconfiguration`.

DIABLO-399, ami.config gets SECURITY_GROUP_AUTOSCALING env var

---

.ebextensions/00_ami.config

No dice. Back to the drawing board. The dev pipeline has been pointed back at repo master.

DIABLO-399, revert use of environment var in aws:autoscaling:launchconfiguration

---

diablo/api/config_controller.py
diablo/jobs/sis_data_refresh_job.py
diablo/lib/development_db_utils.py
diablo/models/development_db.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-415
`instructor_emails_job` crashed because we had approvals for non-existent courses.

DIABLO-415, sis_data_refresh deletes 'pilot' courses in sis_sections; we must delete related objects

---

.ebextensions/00_ami.config
scripts/codebuild/assign-security-groups.sh

I've added env var `DIABLO_PROD_PIPELINE` to build stage of the prod pipeline.

[release] DIABLO-399, security-groups on release branch; test shell script on benign entries in 00_ami.config

---

src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-364
Baby steps: let's make sure Xena can reliably click button without kicking off multiple job instances.

DIABLO-364, run job with conventional v-btn; extra insurance to not run a running job

---

package-lock.json
package.json

We'll see if Vuetify is to blame for sudden bad behavior on `/jobs`

NOJIRA, roll back Vuetify 2.3.0 to troubleshoot /jobs

---

.ebextensions/00_ami.config

PR #289 was merged and deployed to prod successfully; the `scripts/codebuild/assign-security-groups.sh` picked up the new CodeBuild env var, as hoped. I expect it to work properly in non-prod environments, too.  This PR is that final step.

DIABLO-399, restore env vars in 00_ami.config; the replace-token script verified in previous PR

---

diablo/api/job_controller.py
diablo/jobs/base_job.py
diablo/models/job_history.py
package-lock.json
package.json
src/api/job.ts
src/components/job/JobHistory.vue
src/components/util/Snackbar.vue
src/views/BaseView.vue
src/views/Jobs.vue
src/views/Login.vue
tests/test_api/test_job_controller.py
xena/pages/jobs_page.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-364
* some front-end weirdness was caused by use of `schedule` in controller
* simplify: toss out `/api/jobs/running` and rely on jobHistory to deduce `job.isRunning` 
* restore vuetify v2.3.0 which was not to blame

DIABLO-364, reduce complexity in Jobs.vue; async job run without 'schedule'

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-364
The goal: no HTTP 504 error when invoking `/api/job/sis_refresh_job/start`  from `/jobs` page. From the client-side, we make that API call in async fashion.

DIABLO-364, sis_refresh_job takes ~2 min to finish; bump Apache timeout to 3 min

---

diablo/models/sis_section.py
fixtures/sis/courses.json
tests/test_api/test_course_controller.py
tests/test_jobs/test_invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-432
'meetings' are ordered by 'startDate', 'startTime'.  I will add similar mock data to our _pilot.json_ in S3.

DIABLO-432, test course data with dual-mode and hybrid instruction

---

config/default.py

This bit us. No `REDSHIFT_SCHEMA_SIS` override was in prod config. All good now.

NOJIRA, we do not want sis_data_ext_dev as default schema

---

diablo/externals/kaltura.py
diablo/jobs/admin_emails_job.py
diablo/jobs/util.py
diablo/lib/kaltura_util.py
diablo/models/email_template.py
diablo/models/scheduled.py
scripts/db/migrate/2020/20200623-DIABLO-413/admin_alert_date_change_template_type.sql
scripts/db/migrate/2020/20200623-DIABLO-413/alter_scheduled_add_start_end_dates.sql
scripts/db/schema.sql
src/components/course/CoursePageSidebar.vue
src/views/Home.vue
tests/test_api/api_test_utils.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_lib/test_berkeley.py
tests/test_lib/test_kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-413
* Start and end dates of a recording are reconciled with (1) dates of meeting and (2) global start/end in Diablo configs.
* The `scheduled` table get `meeting_end_date` and `meeting_start_date` columns
* New email template: admin_alert_date_change

DIABLO-413, email template: admin_alert_date_change; scheduled table gets start/end dates

---

diablo/models/sis_section.py
src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/views/CourseChanges.vue
src/views/Home.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-444
For now we compare date values as strings; this will change with https://jira.ets.berkeley.edu/jira/browse/DIABLO-456.
We also switch the course API feed over from highlighting `meetingDateRangesVary` to `nonstandardMeetingDates`.

DIABLO-444 Display meeting date changes on Course Changes page

---

diablo/jobs/admin_emails_job.py
diablo/jobs/util.py
diablo/models/development_db.py
diablo/models/scheduled.py
diablo/models/sis_section.py
diablo/sql_templates/update_rds_sis_sections.template.sql
scripts/db/migrate/2020/20200624-DIABLO-456/column_type_timestamp_for_meeting_dates.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-456
The db/migrate scripts worked locally, with non-empty tables. I have not tested with type casting in `update_rds_sis_sections.template.sql`.

DIABLO-456, meeting dates in sis_sections and scheduled are now timestamps

---

diablo/externals/kaltura.py
diablo/lib/berkeley.py
diablo/lib/kaltura_util.py
tests/test_api/test_course_controller.py
tests/test_lib/test_berkeley.py
tests/test_lib/test_kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-464
Recording-end-date config '2020-11-24' is a Tuesday and the course meets ['MO','WE','FR'], thus we expect '2020-11-23' from `get_recording_end_date(meeting)`

DIABLO-464, recording_start/end calculated with course.meeting.days in mind

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-483
I'm reverting PR #368. It seems that `base_entry` name is used in multiple places.

DIABLO-483, kaltura_base_entry name is used in multiple places; investigation needed

---

diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-487
If course has multiple instructors and one drops off then `has_obsolete_instructors` is false.

DIABLO-487, has_obsolete_instructors if current instructors not subset of uids of scheduled

---

diablo/jobs/admin_emails_job.py
diablo/models/scheduled.py
scripts/db/migrate/2020/20200703-DIABLO-490/alter_scheduled_table_add_alerts.sql
scripts/db/schema.sql
src/components/course/ScheduledCourse.vue
tests/test_api/api_test_utils.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-490
Add column `alerts`, an array of email_template_types, to the `scheduled` table.
When a bogus schedule is unscheduled, emails to admin will be sent again if the course suffers more change in dates/times, rooms, etc.

DIABLO-490, admin_alert is sent again if the 'scheduled' record is new

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
diablo/lib/interpolator.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-489
When sending room-change alerts, we want ineligible meeting info if no eligible is found.

DIABLO-489, template codes for ineligible-room and instructor emails

---

config/default.py
diablo/externals/b_connected.py
diablo/merged/emailer.py
tests/test_jobs/test_admin_emails_job.py
tests/test_jobs/test_instructor_emails_job.py
tests/test_lib/test_interpolator.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-502
IMO, better than managing custom email list. Review with `?w=1`

DIABLO-502, EMAIL_SYSTEM_ERRORS can be addresses (list) or address (string)

---

diablo/api/course_controller.py
diablo/externals/b_connected.py
diablo/jobs/background_job_manager.py
diablo/jobs/kaltura_job.py
diablo/jobs/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-510
A little cleanup here. We want `/api/course/approve` to use `get_courses_ready_to_schedule()` instead of homegrown `is_ready_to_schedule` logic. My next PR will have a fixes for DIABLO-510 and https://jira.ets.berkeley.edu/jira/browse/DIABLO-487

DIABLO-510, logic of get_courses_ready_to_schedule() is now shared

---

diablo/jobs/util.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-487
* Do not schedule if `not has_admin_approval` and `not approved_by_uids.issubset(instructor_uids)`.
* After scheduled, surface course on `/changes` if course_instructors not equal to scheduled_instructors

DIABLO-487, course on /changes if instructor drops off; more validation in schedule_recordings()

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-513

DIABLO-513, Kaltura API call: use default tz for recording_end_date, time(23, 59)

---

diablo/api/job_controller.py
diablo/models/job_history.py
src/api/job.ts
src/components/course/CourseRoom.vue
src/components/course/CoursesDataTable.vue
src/components/course/Instructor.vue
src/components/course/ObsoleteSchedule.vue
src/mixins/Utils.vue
src/views/CourseChanges.vue
tests/test_api/test_job_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-512
Overhaul of course-changes page. (The old UX is still present, down the page from this new UX. The old will be removed if the new is judged as better.) In this design, if scheduled room is obsolete then we do not show scheduled dates and times, because a room change makes that other info irrelevant. 
Notice in screenshot that much is communicated via icons. Mouse-over icon always gives info. The hope is that Willa will become versed in semantics o' icon.

DIABLO-512, new UX for course changes page

---

diablo/lib/development_db_utils.py
diablo/models/sis_section.py
fixtures/sis/courses.json
src/components/course/CoursesDataTable.vue
src/components/course/ObsoleteSchedule.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-514
Queries in which we tolerate null instructor:
- get_course
- get_course_changes
- get_courses_invited
- get_courses_opted_out
- get_courses_queued_for_scheduling
- get_courses_per_location
I have a test to verify invitations_job skips null instructors.

DIABLO-514, certain sis_section queries (course-changes; already-scheduled) tolerate null instructor-uid

---

diablo/jobs/admin_emails_job.py
diablo/lib/berkeley.py
diablo/models/sis_section.py
src/components/course/ObsoleteSchedule.vue
tests/test_api/api_test_utils.py
tests/test_jobs/test_admin_emails_job.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-521
The bug was in `sis_section` feed:
```
'hasObsoleteDates': is_schedule_obsolete(meeting=meeting, scheduled=scheduled),
```
A change in days/times was producing `True` above and that is wrong. I fixed and adjusted logic in `AdminEmailsJob`.

DIABLO-521, split is_schedule_obsolete into separate date and time checks

---

src/components/kaltura/KalturaEventList.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-524
Sorting is not useful – and was mostly disabled – in these views.

DIABLO-524, shorthand for disable-sort on /home, /email/templates, and /jobs

---

src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-525
The schedule package we use [does not support timezones](https://schedule.readthedocs.io/en/stable/faq.html#does-schedule-support-timezones) so instead of home-cooked UTC-offset logic we assume all `day_at` configs are UTC.  UI label is the only change needed.

DIABLO-525, day_at job schedules are UTC

---

diablo/api/kaltura_controller.py
diablo/routes.py
tests/test_api/test_kaltura_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-544
A quick answer to question, does Kaltura know about this course site?

DIABLO-544, API endpoint to get Kaltura metadata per canvas_course_site_id

---

src/assets/styles/diablo-global.css
src/components/util/Days.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-531
https://www.powermapper.com/tests/screen-readers/labelling/acronym-abbr-title/
We'll see if NVDA `abbr` support is on by default.

DIABLO-531, abbr tag for accessible abbreviations

---

diablo/models/sis_section.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-548
Changes:
* cleaned up SQL formatting
* `get_courses` query now uses `instructor_uid IS NULL OR instructor_role_code IN ('ICNT', 'PI', 'TNIC')`
* I decided not to touch the complex `get_courses_partially_approved` query.  A course with zero instructors and approvals in the past will not show up in the associated filter.

DIABLO-548, courses with zero instructors show up on /ouija

---

diablo/api/auth_controller.py
diablo/api/user_controller.py
diablo/models/sis_section.py
diablo/models/user.py
tests/test_api/test_auth_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-560
Previously, the `courses_per_uid` query happened 2-3 times per front-end view. Does not scale well.

DIABLO-560, do not fetch courses_per_uid every time flask_login loads user

---

diablo/lib/development_db_utils.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-471
Also, I added SQL-type cast in load-mock-courses in order to match `sis_sections.template.sql`.

DIABLO-471, SQL tweak to non-standard filter: odd start_date is relevant only if scheduled beforehand

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-567
It seems that Kaltura just fixed a bug whereby co-editors could publish. We must adapt.

DIABLO-567, instructors get co-edit and co-publish perms in Kaltura series

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-554
This kind of fix worked for DIABLO-364. We now have secondary sections in the mix and certain jobs (eg, Canvas) take longer. I'm increasing timeout to 10 min. If this problem happens again then we'll probably want to introduce job_status polling in Diablo.

DIABLO-554, 'TimeOut 600' in Apache config for long running jobs

---

config/default.py
diablo/externals/canvas.py
diablo/jobs/canvas_job.py
diablo/lib/berkeley.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-593
Maintaining CANVAS_ENROLLMENT_TERM_ID config is prone to error. Deducing on the fly ain't hard.

DIABLO-593, programmatically get canvas_enrollment_term_id per CURRENT_TERM_ID config

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-599
If `currentTermId !== course.termId` then show no such dates.

DIABLO-599, course page sidebar: show recording start/end dates

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-600
The leading dash is intentional (see [related post](https://stackoverflow.com/questions/50489593/orderby-filter-not-working-for-kaltura-media-listing-api-using)).

DIABLO-600, Kaltura API: get_events_by_location order by startDate

---

scripts/db/migrate/2021/20210601-DIABLO-628/add_blackouts_job.sql
src/views/blackout/Blackouts.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-628
And, no need to show 'createdAt' on /blackouts page.  It might get confused with the blackout date range.
Release instructions updated with db modify script in this PR.

DIABLO-628, add 'blackouts' job to db

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-649
PR to custom branch, for AWS codeDeploy testing.

DIABLO-649, AWS linux-2: remove obsolete 'aws:elasticbeanstalk:container:python:staticfiles' config

---

README.md
diablo/api/course_controller.py
diablo/jobs/util.py
diablo/models/approval.py
diablo/models/scheduled.py
scripts/db/migrate/2021/20210924-DIABLO-654/add_course_display_name_column.sql
scripts/db/schema.sql
tests/test_api/api_test_utils.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_admin_emails_job.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-677
We'll use `course_display_name` when course is cancelled and we have no SIS data per section_id. (Release instructions updated.)
*Note:* The reordering of args in certain methods is only alpha sort.

DIABLO-677, add course_display_name to db: approvals and scheduled
