scripts/db/add_admin_user.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-42

DIABLO-42, SQL script to add Diablo admin user

---

config/default.py
diablo/api/sign_up_controller.py
diablo/externals/data_loch.py
diablo/merged/sis.py
diablo/models/development_db.py
diablo/models/sign_up.py
diablo/models/user.py
diablo/routes.py
fixtures/calnet_user_for_uid_234567.json
fixtures/loch.sql
scripts/db/drop_schema.sql
scripts/db/schema.sql
tests/test_api/test_sign_up_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-66

DIABLO-66, API endpoint: /api/sign_up/status/<term_id>/<section_id>

---

.eslintrc.js
diablo/merged/sis.py
src/App.vue
src/api/api-utils.ts
src/api/auth.ts
src/mixins/Utils.vue
src/views/Home.vue
src/views/Login.vue
src/views/SignUp.vue
tests/test_api/test_sign_up_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-63
Next, the form and the necessary API.

DIABLO-63, sign-up page takes shape

---

config/default.py
diablo/api/config_controller.py
src/App.vue
src/assets/styles/diablo-global.css
src/views/SignUp.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-64

DIABLO-64, Course Capture sign-up form, a work in progress

---

diablo/api/approval_controller.py
diablo/lib/berkeley.py
diablo/models/scheduled.py
scripts/db/drop_schema.sql
scripts/db/schema.sql
src/views/Approve.vue
tests/test_api/test_approval_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-47
When `hasNecessaryApprovals` then the sign-up view is read-only. The `scheduled` db table is updated when Kaltura transaction is done.

DIABLO-47, approval by admin or all instructors will shut down sign-up form

---

config/default.py
config/test.py
diablo/api/approval_controller.py
diablo/api/config_controller.py
diablo/api/job_controller.py
diablo/api/report_controller.py
diablo/lib/berkeley.py
diablo/models/approval.py
diablo/models/scheduled.py
diablo/models/user.py
diablo/routes.py
fixtures/edo_db/all_courses_2202.json
fixtures/loch.sql
fixtures/salesforce/all_rooms.json
fixtures/salesforce/capture_enabled_rooms.json
scripts/db/drop_schema.sql
scripts/db/schema.sql
src/api/report.ts
src/views/Rooms.vue
tests/test_api/test_approval_controller.py
tests/test_api/test_config_controller.py
tests/test_api/test_report_controller.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-64
Reports!

DIABLO-64, admin view of all rooms includes approvals and scheduled

---

diablo/api/report_controller.py
src/views/Approve.vue
src/views/Ouija.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-67

DIABLO-67, admin-only view listing courses with approvals, scheduled recordings

---

config/default.py
diablo/__init__.py
diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/DIABLO-109

DIABLO-109, Kaltura connection status to /api/ping result

---

diablo/externals/kaltura.py
diablo/externals/salesforce.py
diablo/jobs/kaltura_job.py
diablo/merged/sis.py
src/App.vue
src/api/report.ts
src/assets/styles/vuetify-overrides.css
src/mixins/Utils.vue
src/views/Ouija.vue
src/views/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-98

DIABLO-98, 'rooms' view; click to view room or instructor summary

---

diablo/api/approval_controller.py
diablo/api/berkeley_controller.py
diablo/api/report_controller.py
diablo/externals/data_loch.py
diablo/jobs/background_job_manager.py
diablo/jobs/update_rooms_job.py
diablo/models/development_db.py
diablo/models/room.py
fixtures/loch.sql
scripts/db/drop_schema.sql
scripts/db/schema.sql
src/api/berkeley.ts
src/assets/styles/diablo-global.css
src/views/Room.vue
src/views/Rooms.vue
tests/test_jobs/test_background_job_manager.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-114

DIABLO-114, /rooms view has select-capability per room

---

config/default.py
diablo/api/job_controller.py
diablo/externals/kaltura.py
diablo/jobs/update_rooms_job.py
diablo/models/development_db.py
diablo/models/room.py
diablo/routes.py
fixtures/kaltura/get_resource_list.json
scripts/db/schema.sql
src/views/Room.vue
src/views/Rooms.vue
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-124
When recordings are scheduled, the resource-id will be ready.

DIABLO-124, rooms table column kaltura_resource_id is maintained by UpdateRoomsJob

---

diablo/api/email_template_controller.py
diablo/models/email_template.py
src/api/email-template.ts
src/components/util/Footer.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-128

DIABLO-128, admin user can delete email templates

---

config/default.py
diablo/api/email_template_controller.py
diablo/externals/mailgun.py
diablo/merged/email.py
diablo/models/user.py
src/mixins/Utils.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue
tests/test_merged/test_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-145
The "only one" rule is based on conversation with Willa.

DIABLO-145, test coverage on email interpolation; only one email template per type

---

config/default.py
diablo/api/auth_controller.py
diablo/api/config_controller.py
diablo/externals/mailgun.py
diablo/merged/emailer.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-139

DIABLO-139, admin-alert emails will be sent to a dedicated address

---

diablo/externals/data_loch.py
fixtures/loch.sql
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-147
Diablo will only surface "teaching" instructors. CourseDataMover had enforced this same rule.

DIABLO-147, only instructors with role_code ICNT, PI, or TNIC

---

diablo/api/course_controller.py
diablo/merged/emailer.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-136

DIABLO-136, approval on a multiple instructor course > send 'Need additional approval' email

---

diablo/api/course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-136
Follow up fix to PR #44

DIABLO-136, fix on uid comparison in notify logic

---

diablo/api/course_controller.py
diablo/api/email_template_controller.py
diablo/api/status_controller.py
diablo/externals/mailgun.py
diablo/jobs/email_alerts_for_admins_job.py
diablo/merged/emailer.py
diablo/merged/sis.py
diablo/models/development_db.py
diablo/models/email_template.py
diablo/models/room.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_merged/test_emailer.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-140
And `/api/ping` gets two more checks: 'emailTemplates' and 'mailgun'.

DIABLO-140, email to admin if room change of already-scheduled course

---

diablo/jobs/email_alerts_for_admins_job.py
diablo/models/approval.py
diablo/models/development_db.py
diablo/models/scheduled.py
fixtures/loch.sql
tests/test_jobs/test_background_job_manager.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-142

DIABLO-142, email admin if an already-scheduled course gets new instructor(s)

---

config/default.py
diablo/externals/mailgun.py
fixtures/calnet/user_for_uid_1015674.json
fixtures/calnet/user_for_uid_2040.json
fixtures/calnet/user_for_uid_234567.json
fixtures/calnet/user_for_uid_8765432.json
fixtures/edo_db/instructors_2202.json

https://jira.ets.berkeley.edu/jira/browse/DIABLO-84

DIABLO-84, if not prod then all emails go to EMAIL_REDIRECT_WHEN_TESTING address

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config
.ebextensions/02_https_instance_single.config
.ebextensions/03_download_local_configuration.config
.ebextensions/10_upgrade_pip.config
.ebextensions/11_set_default_region.config
.ebextensions/99_delayed_script.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-58
BOA was my guide. Although I excluded `mpm_worker`, `cloudwatch`, and `pandas`.
https://jira.ets.berkeley.edu/jira/browse/DIABLO-59 will address the TODOs.

DIABLO-58, .ebextensions for Diable with some TODOs (eg, SSL certs)

---

diablo/api/job_controller.py
diablo/externals/data_loch.py
diablo/jobs/data_loch_sync_job.py
diablo/lib/util.py
diablo/merged/sis.py
diablo/models/development_db.py
diablo/models/sis_section.py
fixtures/loch.sql
scripts/db/drop_schema.sql
scripts/db/schema.sql
src/views/Ouija.vue
src/views/room/Rooms.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-73
When we cutover to db_link setup, the sync-job will run a `sql_template` script instead of SQL query against data_loch.  This PR speeds up front-end substantially.

DIABLO-73, prep for db_link with sis_section in local RDS; job syncs with data_loch

---

.ebextensions/03_download_local_configuration.config
diablo/api/course_controller.py
diablo/merged/sis.py
diablo/models/approval.py
diablo/models/room.py
diablo/models/scheduled.py
src/components/util/Footer.vue
src/views/BaseView.vue
src/views/Home.vue
src/views/Ouija.vue
src/views/User.vue
src/views/email/EmailTemplates.vue
src/views/room/PrintableRoom.vue
src/views/room/Room.vue
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_kaltura_job.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-149
And...
* S3 path fix per Ops' latest work
* disable pagination, for now
* use `?w=1` for clearer diff in `tests/`

DIABLO-149, admin dashboard filters impl'd: Invited, Not Invited, Do Not Email

---

diablo/models/admin_user.py
diablo/models/development_db.py
scripts/db/schema.sql
tests/test_api/test_auth_controller.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-169
You can delete an admin user but you can't delete her paper trail.

DIABLO-169, add 'deleted_at' column to users table

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-55

DIABLO-55, fix copy and paste errors in .ebextensions

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-58

DIABLO-58, aws:elbv2:loadbalancer > SecurityGroups config

---

diablo/api/course_controller.py
diablo/models/sis_section.py
src/views/Ouija.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-150
https://jira.ets.berkeley.edu/jira/browse/DIABLO-154
Design in https://jira.ets.berkeley.edu/jira/browse/DIABLO-132

DIABLO-150, show course status per Course Capture workflow on /ouija

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-59

DIABLO-59, arn:aws:acm for SSL cert

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-130

DIABLO-130, .ebextensions get certs and such

---

.ebextensions/00_ami.config

We'll circle back to logging-in-the-cloud.

NOJIRA, no Cloudwatch, for now

---

config/default.py
config/test.py
diablo/api/job_controller.py
diablo/jobs/admin_emails_job.py
diablo/jobs/background_job_manager.py
diablo/jobs/base_job.py
diablo/jobs/canvas_job.py
diablo/jobs/data_loch_sync_job.py
diablo/jobs/dblink_to_redshift_job.py
diablo/jobs/kaltura_job.py
diablo/jobs/queued_emails_job.py
diablo/lib/util.py
diablo/models/admin_user.py
diablo/models/development_db.py
diablo/models/job_history.py
diablo/models/sis_section.py
scripts/db/drop_schema.sql
scripts/db/schema.sql
src/App.vue
src/api/job.ts
src/router.ts
src/views/CourseChanges.vue
src/views/JobHistory.vue
src/views/Jobs.vue
src/views/Ouija.vue
tests/test_api/test_job_controller.py
tests/test_jobs/sample_jobs.py
tests/test_jobs/test_background_job_manager.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-171
See screenshots attached to the Jira above.
PR also includes `/job/history` view:

DIABLO-171, /changes view shows approval status per instructor and per admin

---

.ebextensions/01_create_apache_conf.config
.ebextensions/10_upgrade_pip.config
diablo/api/status_controller.py
diablo/externals/canvas.py
diablo/externals/rds.py
requirements.txt
vue.config.js

https://jira.ets.berkeley.edu/jira/browse/DIABLO-173

DIABLO-173, the tweaks that appeased CodePipeline and eb-deploy

---

diablo/api/auth_controller.py
diablo/api/status_controller.py
src/App.vue
src/api/auth.ts
src/components/email/TemplateCodesDialog.vue
src/main.ts
src/mixins/Context.vue
src/router.ts
src/store/modules/context.ts
src/views/Approve.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/Ouija.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-151
CodePipeline failed with actual `/api/ping` tests. I'm going to tackle the health checks after we get latest code up in dev env.

DIABLO-151, ids on buttons, form inputs, etc. Plus, always-happy /api/ping for now

---

diablo/api/status_controller.py
diablo/externals/kaltura.py
diablo/models/approval.py
diablo/models/scheduled.py
diablo/models/sis_section.py
scripts/db/schema.sql
scripts/get_config_file_from_s3.sh
tests/test_api/test_config_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_email_controller.py
tests/test_api/test_job_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-171
And bug fixes made along the way.

DIABLO-171, '/course/changes' test coverage; and scripts/get_config_file_from_s3.sh

---

diablo/externals/mailgun.py
diablo/jobs/queued_emails_job.py
diablo/merged/emailer.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-162

DIABLO-162, QueuedEmailsJob only delete from queue if successful send; do not email if course opted out

---

diablo/api/email_controller.py
diablo/jobs/queued_emails_job.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_kaltura_job.py
tests/test_jobs/test_queued_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-131

DIABLO-131, test coverage: queued_emails_job and kaltura_job

---

diablo/api/room_controller.py
diablo/models/sis_section.py
tests/test_api/test_course_controller.py
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-176
Reqts described in https://jira.ets.berkeley.edu/jira/browse/DIABLO-175

DIABLO-176, Search filter concerns: In eligible room? Received invitation? Approvals?

---

diablo/models/room.py
tests/test_api/test_course_controller.py
tests/test_api/test_email_controller.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-175

DIABLO-175, test coverage for search filters

---

diablo/api/room_controller.py
diablo/api/user_controller.py
diablo/api/util.py
diablo/models/sis_section.py
src/components/room/SelectRoomCapability.vue
src/views/Ouija.vue
src/views/room/PrintableRoom.vue
src/views/room/Room.vue
src/views/room/Rooms.vue
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-204
https://jira.ets.berkeley.edu/jira/browse/DIABLO-205

DIABLO-205, /room behaves w.r.t auditorium; fix printable view

---

src/assets/styles/diablo-global.css
src/views/room/PrintableRoom.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-202

DIABLO-202, printable-room lists only scheduled courses

---

config/default.py
diablo/api/config_controller.py
src/assets/styles/diablo-global.css
src/components/course/CoursesDataTable.vue
src/components/room/SelectRoomCapability.vue
src/mixins/Utils.vue
src/views/Ouija.vue
src/views/User.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-209

DIABLO-209, reusable CoursesDataTable for /ouija, /room, /user

---

diablo/sql_templates/update_rds_sis_sections.template.sql
scripts/db/drop_schema.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-217
Someone with more `dblink` experience should have a look.

DIABLO-217, do not drop 'sis_sections' table when dblink refresh; preserve past term data

---

diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-192

DIABLO-192, courses API feed must include cross-listings info per course

---

diablo/api/course_controller.py
diablo/lib/berkeley.py
diablo/merged/calnet.py
diablo/models/approval.py
diablo/models/sis_section.py
package-lock.json
package.json
src/components/course/CoursesDataTable.vue
src/components/course/CrossListingTooltip.vue
src/main.ts
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Home.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-193

DIABLO-193, courses with cross-listings have tooltip in list and /course view

---

diablo/models/cross_listing.py
src/App.vue
src/components/course/CoursesDataTable.vue
src/components/util/Snackbar.vue
src/views/BaseView.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Error.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/NotFound.vue
src/views/Ouija.vue
src/views/User.vue
src/views/email/EditEmailTemplate.vue
src/views/room/Room.vue
src/views/room/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-230
And some accessibility tweaks: sr-only 'skip to content' and better use of headers.

DIABLO-230, CrossListing.refresh break massive SQL insert into chunks

---

diablo/models/course_preference.py
diablo/models/sis_section.py
src/components/course/CoursesDataTable.vue
src/components/util/Footer.vue
src/views/BaseView.vue
src/views/Course.vue
src/views/Home.vue
src/views/Ouija.vue
src/views/User.vue
src/views/room/Room.vue
src/views/room/Rooms.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-232
https://jira.ets.berkeley.edu/jira/browse/DIABLO-197
If a course "opts out" then its cross-listings are opted out.

DIABLO-232, 'GROUP BY' in cross-listings lookup; clean up instructor /home UX

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-232

DIABLO-232, distinct on section_id in find-cross-listings query

---

src/components/util/OxfordJoin.vue
src/views/Course.vue
src/views/room/PrintableRoom.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-203
https://jira.ets.berkeley.edu/jira/browse/DIABLO-235
Plus, new `OxfordJoin` component uses slot to render each item.

DIABLO-203, /room/printable gets instructor names (and v-app)

---

diablo/api/course_controller.py
diablo/jobs/dblink_to_redshift_job.py
diablo/jobs/kaltura_job.py
diablo/models/approval.py
diablo/models/cross_listing.py
diablo/models/development_db.py
diablo/models/scheduled.py
diablo/models/sis_section.py
scripts/db/migrate/2020/20200429-DIABLO-239/modify_cross_listings_strategy.sql
scripts/db/schema.sql
src/components/room/SelectRoomCapability.vue
src/views/Course.vue
src/views/Ouija.vue
src/views/email/EmailTemplates.vue
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-239
The Jira explains strategy. The collapsing of cross-listed course names into a single name/title, and additional test coverage, will come in subsequent PR.

DIABLO-239, cross-listed section_ids only available in cross_listings table; they are 'deleted' in sis_sections

---

config/xena.py
src/views/Course.vue
xena/README.md
xena/pages/login_page.py
xena/pages/ouija_board_page.py
xena/pages/page.py
xena/pages/sign_up_page.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-246
ids on <label> element (in `Course.vue`) is a workaround the unclickable v-select issue.

DIABLO-246, Xena uses app.config[...] instead of config.xena; xpath for v-select

---

diablo/models/sis_section.py
fixtures/calnet/user_for_uid_10009.json
fixtures/calnet/user_for_uid_10010.json
fixtures/sis/courses.json
tests/test_api/test_course_controller.py
tests/test_api/test_user_controller.py
tests/test_jobs/test_queued_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-247
Work remains. For example, when determining `hasNecessaryApprovals` per course.

DIABLO-247, if section X, Y, and Z are cross-listed then /course page of X must be reachable by instructor of Z

---

src/assets/styles/diablo-global.css
src/views/BaseView.vue
src/views/Login.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-234

DIABLO-234, redesigned login page

---

.eslintrc.js
src/components/course/CoursesDataTable.vue
src/components/course/CrossListingTooltip.vue
src/components/email/TemplateCodesDialog.vue
src/components/util/Footer.vue
src/components/util/Snackbar.vue
src/views/BaseView.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/Ouija.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue
src/views/room/PrintableRoom.vue
src/views/room/Room.vue
src/views/room/Rooms.vue

I'm testing CodePipeline and taking opportunity to enable the `vue/html-closing-bracket-newline` eslint rule.

NOJIRA, add a few eslint rules and fix offending code

---

diablo/api/job_controller.py
diablo/models/canvas_course_site.py
diablo/models/sis_section.py
fixtures/canvas/canvas_course_sites.json
src/api/job.ts
src/views/Jobs.vue
tests/test_api/test_job_controller.py
tests/test_jobs/sample_jobs.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-249
https://jira.ets.berkeley.edu/jira/browse/DIABLO-248

DIABLO-249, show job schedule on /jobs; all canvas-sites for KalturaJob

---

diablo/jobs/base_job.py
diablo/models/job_history.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-251
Review with `?w=1` and you'll see that this is a simple change.

DIABLO-251, do not allow two or more jobs of the same type to run concurrently

---

diablo/models/canvas_course_site.py
tests/test_api/api_test_utils.py
tests/test_jobs/test_canvas_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-250

DIABLO-250, CanvasJob: no more 'violates unique constraint canvas_course_sites_pkey'

---

diablo/api/course_controller.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-220

DIABLO-220 Back end for course unscheduling

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-253
Review with `?w=1` for simpler diff.

DIABLO-253, if no email template per type then raise proper error

---

src/api/course.ts
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-221

BOAC-221 Front end for course unscheduling

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/kaltura_job.py
diablo/merged/emailer.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-253
One more fix of the "template not available" sort.

DIABLO-253, if email_template is unavailable then notify admin

---

config/default.py
diablo/externals/kaltura.py
diablo/jobs/base_job.py
diablo/jobs/kaltura_job.py
diablo/logger.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-129

DIABLO-129, minor logging-related fixes; quiet down werkzeug

---

diablo/api/course_controller.py
diablo/api/util.py
diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-256
Also consolidate some test code.

DIABLO-256 Ouija board 'all' filter

---

diablo/api/room_controller.py
diablo/externals/kaltura.py
diablo/lib/kaltura_util.py
diablo/lib/util.py
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-258
Having raw JSON of already-scheduled recordings will help in coding our API calls to schedule.

DIABLO-258, use Kaltura API to pull scheduled recordings per room; display on /room page

---

diablo/externals/kaltura.py
diablo/lib/kaltura_util.py
diablo/lib/util.py
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-258
This PR is sequel of #124

DIABLO-258, group scheduled-events by parent/child; parents are 'recurring' and children are 'recurrence'

---

.eslintrc.js
diablo/externals/kaltura.py
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-244
For the first time, the Kaltura API returned a '200' response status. The next step is to see what – if anything – was created in the Kaltura event calendar. Nonetheless, this is a step forward.
I've put in more TODOs based on what the API complained about.

DIABLO-244, Kaltura API success with add recurring_event

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-259

DIABLO-259 TAs off the room pages

---

src/components/course/CoursesDataTable.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-264

DIABLO-264 Fix courses table pagination

---

diablo/jobs/base_job.py
diablo/merged/emailer.py
tests/test_jobs/sample_jobs.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-243

DIABLO-243 Admin email on job failure

---

src/components/course/CoursesDataTable.vue
src/views/Course.vue
src/views/Ouija.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-266
https://jira.ets.berkeley.edu/jira/browse/DIABLO-273

DIABLO-266 DIABLO-273 Move invite button off Ouija Board, onto course page

---

diablo/externals/kaltura.py
diablo/jobs/background_job_manager.py
diablo/jobs/util.py
diablo/models/sis_section.py
tests/conftest.py
tests/test_api/test_job_controller.py
tests/test_merged/test_emailer.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/DIABLO-274

DIABLO-274, fix datetime references in Kaltura API call

---

config/xena.py
xena/conftest.py
xena/fixtures/test-rooms.json
xena/models/recording_type.py
xena/models/room.py
xena/pages/diablo_pages.py
xena/pages/jobs_page.py
xena/pages/page.py
xena/pages/room_page.py
xena/pages/rooms_page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_enable_rooms.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py

- Adds a "test" to set the capabilities of rooms
- Adds three additional sign-up workflow tests (more still to come)

More sign-up tests

---

diablo/api/course_controller.py
diablo/jobs/kaltura_job.py
diablo/jobs/util.py
diablo/models/approval.py
requirements.txt
src/api/course.ts
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-104
This will speed up my testing of Kaltura API calls and, possibly, be useful to our admin.
Admin users get:

DIABLO-104, admin can approve, and optionally schedule, from /course page

---

diablo/jobs/instructor_emails_job.py
tests/test_jobs/test_instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-262

DIABLO-262 Send invites from instructor emails job

---

diablo/externals/kaltura.py
diablo/jobs/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-104
Plus, error handling in `kaltura_job`

DIABLO-104, with scheduleEvent.add API, attach Kaltura schedule to room (resource)

---

config/xena.py
xena/conftest.py
xena/models/recording_schedule.py
xena/models/section.py
xena/pages/kaltura_page.py
xena/test_utils/util.py
xena/tests/test_kaltura_schedule.py

This doesn't do anything yet, but it lays the groundwork for verifying Diablo-scheduled recordings in the Kaltura UI.

Initial Kaltura UI interactions

---

src/views/Course.vue
src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-281
Addresses one of many concerns described in the Jira.

DIABLO-281, admin user does not need to agree to terms

---

diablo/merged/emailer.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-255
One confirmation email per instructor.

DIABLO-255, 'instructor.name' rendered in 'recordings_scheduled' email

---

config/default.py
diablo/externals/kaltura.py
diablo/jobs/util.py
src/views/Login.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-284
Two tweaks seemed to make the difference:
* added `templateEntryId` to API call
* fixed value of `recurrence.until`

DIABLO-284, Kaltura recurrences created properly and series is editable

---

diablo/models/cross_listing.py
diablo/models/sent_email.py
diablo/models/sis_section.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_kaltura_job.py
tests/test_jobs/test_queued_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-276

DIABLO-276 Rewrite course API feed for performance

---

config/default.py
config/test.py
diablo/api/job_controller.py
diablo/factory.py
diablo/jobs/background_job_manager.py
diablo/jobs/base_job.py
diablo/jobs/doomed_to_failure.py
diablo/models/development_db.py
diablo/models/job.py
scripts/db/drop_schema.sql
scripts/db/migrate/2020/20200514-DIABLO-294/add_jobs_table.sql
scripts/db/schema.sql
tests/test_api/test_job_controller.py
tests/test_jobs/test_background_job_manager.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-294

DIABLO-294, jobs config moves to db; prep for 'disabled' toggle on /jobs

---

scripts/db/migrate/2020/20200514-DIABLO-294/add_jobs_table.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-294

DIABLO-294, db/migrate script must set owner to app_diablo

---

diablo/api/course_controller.py
diablo/models/approval.py
diablo/models/scheduled.py
scripts/db/migrate/2020/20200515-DIABLO-271/schedule_approval_soft_delete.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-271

DIABLO-271 Soft delete for approvals, scheduled

---

diablo/models/approval.py
diablo/models/scheduled.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-271
Follow-up to #152.
Local tox is as green as an unchlorinated swimming pool.

DIABLO-271 Adapt some models to the new normal

---

diablo/api/job_controller.py
diablo/jobs/base_job.py
diablo/models/development_db.py
diablo/models/job.py
src/api/job.ts
src/views/Jobs.vue
tests/test_api/test_job_controller.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-294
In order to run, a job must be registered in the db.

DIABLO-294, on /jobs page, disable or run job; and schedule is prominent in view

---

diablo/externals/b_connected.py
diablo/jobs/queued_emails_job.py
diablo/models/queued_email.py
scripts/db/migrate/2020/20200518-DIABLO-318/pad_out_queued_emails.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-308

DIABLO-308 Allow queued email messages to interpolate before sending

---

diablo/jobs/instructor_emails_job.py
diablo/merged/emailer.py
diablo/models/queued_email.py
tests/test_jobs/test_instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-309

DIABLO-309 Move instructor emails to queue

---

diablo/factory.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-319

DIABLO-319, use WERKZEUG_RUN_MAIN to avoid extra background_job threads at startup

---

diablo/jobs/admin_emails_job.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-310

DIABLO-310 Move admin notifications to email queue

---

diablo/api/course_controller.py
diablo/api/email_controller.py
diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/util.py
diablo/lib/interpolator.py
diablo/merged/emailer.py
diablo/models/queued_email.py
scripts/db/migrate/2020/20200518-DIABLO-318/pad_out_queued_emails.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
tests/test_jobs/test_kaltura_job.py
tests/test_lib/test_interpolator.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-312
https://jira.ets.berkeley.edu/jira/browse/DIABLO-313

DIABLO-312 DIABLO-313 Move remaining email types into queue

---

diablo/api/course_controller.py
diablo/api/room_controller.py
diablo/externals/kaltura.py
scripts/commands.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-296
Delete events tagged 'created_by_diablo'.
Run script with:
```
export FLASK_APP=scripts/commands.py
FLASK_ENV=development flask delete_scheduled_events_from_kaltura
```

DIABLO-296, script to delete the created_by_diablo events from Kaltura

---

diablo/externals/b_connected.py
diablo/jobs/queued_emails_job.py
diablo/models/queued_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-328

DIABLO-328 Safeguards against unsendable email

---

diablo/models/sis_section.py
fixtures/sis/courses.json
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-329

DIABLO-329, /ouija: exclude deleted in 'Scheduled' and 'Partially Approved' results

---

diablo/api/email_controller.py
diablo/models/queued_email.py
src/api/email.ts
src/views/Course.vue
tests/test_jobs/test_queued_emails_job.py
tests/test_models/test_queued_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-326
Emails missing templates, courses or instructors will return an error instead of hanging around in the queue.

DIABLO-326 Don't queue unsendable emails

---

config/default.py
diablo/externals/kaltura.py
diablo/lib/kaltura_util.py
requirements.txt
scripts/commands.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-322
Jira has links to Kaltura API docs.

DIABLO-322, use KalturaBlackoutScheduleEvent to set holidays, avoid pointless recordings

---

diablo/jobs/queued_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-332

DIABLO-332 QueuedEmailsJob shouldn't exit early

---

diablo/lib/kaltura_util.py
tests/test_lib/test_kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-320

DIABLO-320, proper timezone localize for start/end times sent to Kaltura

---

diablo/jobs/background_job_manager.py
diablo/models/job_history.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-333

DIABLO-333 Clean up job history on instance restart

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-326

DIABLO-326 Front end: no send-invite button if no instructors

---

diablo/externals/kaltura.py
diablo/jobs/util.py
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-288

DIABLO-288, in Kaltura, category_ids map to Canvas course sites

---

diablo/externals/kaltura.py
diablo/jobs/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-288
Previous PR was missing this translation.

DIABLO-288, translate canvas_course_site_ids to category_ids prior to schedule

---

diablo/api/course_controller.py
diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/queued_emails_job.py
diablo/lib/interpolator.py
diablo/models/queued_email.py
scripts/db/migrate/2020/20200518-DIABLO-318/pad_out_queued_emails.sql
scripts/db/schema.sql
tests/test_jobs/test_instructor_emails_job.py
tests/test_jobs/test_queued_emails_job.py
tests/test_lib/test_interpolator.py
tests/test_models/test_queued_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-301

DIABLO-301 Interpolate all email when queued

---

diablo/api/email_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-301
Follow-up to #183.

DIABLO-301 Follow-up interpolation fixes

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-336

DIABLO-336 Course queries return primary sections only

---

diablo/api/room_controller.py
diablo/lib/kaltura_util.py
src/views/Course.vue
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-317

DIABLO-317, /rooms/auditorium is available to all, not just admins

---

diablo/api/job_controller.py
diablo/jobs/base_job.py
diablo/models/development_db.py
src/views/Course.vue
tests/test_api/test_job_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-341
Xena needs this fix so it was fast-tracked.

DIABLO-341, disabled job runs when invoked by /api/job/<job_key>/start

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-279

DIABLO-279 Show multiple approvals on course page

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-280

DIABLO-280 Insist on accuracy in "Partially Approved" label

---

diablo/externals/kaltura.py
src/views/BaseView.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-81

DIABLO-81, assign collaborators when Kaltura series created if publish_type == my_media

---

diablo/externals/kaltura.py
diablo/jobs/base_job.py
diablo/jobs/kaltura_job.py
diablo/lib/kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-81
Collaborators in Kaltura will match list o' course instructors. I'll create a reqts Jira to better understand necessary permissions and potential edge cases.

DIABLO-81, scheduled courses get collaborators add/remove per instructor changes

---

diablo/externals/b_connected.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-342

DIABLO-342 Remove admin bcc from outgoing mail

---

diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-344
Per Willa's comments in https://jira.ets.berkeley.edu/jira/browse/DIABLO-343

DIABLO-344, add collaborators (instructors) to Kaltura series, no matter the publish_type

---

diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py
diablo/lib/kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-343
See requirements clarification in the Jira.
Review with `?w=1` for a simpler diff.

DIABLO-343, set collaborators when recordings scheduled; do not update, no matter instructor changes

---

xena/test_utils/util.py

NOJIRA, Xena db.execute needs std_commit: allow_test_environment

---

diablo/api/email_controller.py
diablo/lib/interpolator.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-338

DIABLO-338 Proper interpolation for email template testing

---

src/components/course/CoursePageSidebar.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-275

DIABLO-275, slim down Course.vue by moving sidebar to dedicated component

---

src/components/course/ScheduledCourse.vue
src/components/util/CourseCaptureExplained.vue
src/components/util/TermsAgreementText.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-275

DIABLO-275, /course page: manageable when modular

---

diablo/models/queued_email.py

DIABLO-348 Remove TODO comment

---

diablo/api/course_controller.py
diablo/externals/kaltura.py
src/components/course/ScheduledCourse.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-275

DIABLO-275, despite recordings scheduled, approval is necessary

---

diablo/jobs/util.py
diablo/models/sis_section.py
fixtures/calnet/user_for_uid_10003.json
src/views/CourseChanges.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-354

DIABLO-354 Display changed times and instructors to admin

---

src/views/CourseChanges.vue

https://github.com/ets-berkeley-edu/diablo/pull/205

DIABLO-354 Course changes page: fix div nesting

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-233
See screenshots in the Jira.

DIABLO-233, no more tooltips on /course

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-81

DIABLO-81, Kaltura API, schedule: instructors are always co-editors

---

diablo/api/course_controller.py
diablo/api/util.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-241

DIABLO-241 Add 'Queued for Scheduling' filter

---

xena/models/section.py
xena/pages/email_page.py
xena/pages/ouija_board_page.py
xena/pages/page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py

These tests will already have been broken by filter changes, but at least the tests are added.

Add filtering to tests

---

diablo/externals/kaltura.py
src/store/modules/context.ts
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-355
Reqts: https://jira.ets.berkeley.edu/jira/browse/DIABLO-357

DIABLO-355, when course is queued or scheduled, instructors see proper messaging

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-225
https://jira.ets.berkeley.edu/jira/browse/DIABLO-325

DIABLO-325, fix wording on /course page and in job descriptions

---

diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-281

DIABLO-281, if course is 'approved' by admin only then it will not show on partially-approval list

---

src/App.vue
src/components/course/CoursePageSidebar.vue
src/components/course/ScheduledCourse.vue
src/components/course/ToggleOptOut.vue
src/components/room/SelectRoomCapability.vue
src/components/util/Footer.vue
src/main.ts
src/mixins/Context.vue
src/mixins/Utils.vue
src/store/modules/context.ts
src/views/BaseView.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Error.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/NotFound.vue
src/views/Ouija.vue
src/views/User.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue
src/views/room/PrintableRoom.vue
src/views/room/Room.vue
src/views/room/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-358
Screen-reader alerts were not working properly. I did cleanup and dropped in more ids.

DIABLO-358, screen-reader alerts; in local-dev, sr alerts show in footer

---

src/components/course/ToggleOptOut.vue
src/views/Ouija.vue
src/views/room/Rooms.vue

ROOM-237, There ain't nothing in Room 237. But you ain't got no business going in there anyway.

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-360

DIABLO-360: One more reqs go-round on the 'Partially Approved' filter

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/kaltura_job.py
src/views/Jobs.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-325

DIABLO-325, explain how and when emails are queued in Diablo

---

diablo/models/development_db.py
diablo/models/room.py
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-335

DIABLO-335, recording type options per room capability and is_auditorium

---

diablo/models/sis_section.py
src/components/course/CoursesDataTable.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-241

DIABLO-241 Split course status into approvalStatus and schedulingStatus

---

diablo/api/course_controller.py
diablo/jobs/util.py
src/components/course/CoursesDataTable.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-363

DIABLO-363 Fix opt-out toggle behavior for scheduled courses

---

src/components/course/CoursePageSidebar.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-229

DIABLO-229 Suppress invites/scheduling for past terms

---

diablo/api/room_controller.py
diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py
diablo/jobs/util.py
diablo/lib/util.py
diablo/routes.py
src/components/kaltura/KalturaEventList.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-320
* Asking clients to page through Kaltura results seems unnecessary and prone to complexity.
* Slim down `Room.vue` by extracting `KalturaEventList`.

DIABLO-320, low-level paging of Kaltura results; component for scheduled events on /room

---

diablo/jobs/admin_emails_job.py
diablo/lib/interpolator.py
diablo/models/development_db.py
tests/test_jobs/test_email_alerts_for_admins.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-349

DIABLO-349 Track discrepancies in instructor-change admin email

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-327

DIABLO-327 No invite available if course has opted out

---

diablo/externals/canvas.py
diablo/jobs/canvas_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-368

DIABLO-368, remove search_term='CHEM' from Canvas API query

---

diablo/externals/canvas.py
diablo/routes.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-368
Log statement added in previous PR is a problem.

DIABLO-368, fix: object of type 'PaginatedList' has no len()

---

diablo/externals/kaltura.py
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/DIABLO-350

DIABLO-350, Kaltura API: collaborators as UIDs; remove nulls

---

diablo/factory.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/invitation_job.py
diablo/models/development_db.py
scripts/db/migrate/2020/20200514-DIABLO-294/add_jobs_table.sql
tests/test_jobs/test_invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-353

DIABLO-353 Move invitations into their own job

---

config/default.py
diablo/__init__.py
diablo/externals/canvas.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-378

DIABLO-378, Canvas API get_courses targets proper sub_account

---

diablo/externals/canvas.py
diablo/models/canvas_course_site.py
fixtures/canvas/canvas_course_sites.json

https://jira.ets.berkeley.edu/jira/browse/DIABLO-379

DIABLO-379, Canvas job: avoid duplicate key error

---

diablo/externals/canvas.py
src/components/util/Footer.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-350

DIABLO-350, Canvas integration: include unpublished and zero enrollment course sites

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-357

DIABLO-357, always list required instructor approvals

---

src/mixins/Context.vue
src/views/Ouija.vue
src/views/User.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-352

DIABLO-352, Ouija board doesn't need to say how many scheduled

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-395

DIABLO-395 Approval(s) needed: pluralization

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-389

DIABLO-389 No need for publishing info after approval

---

xena/models/async_job.py
xena/models/recording_approval_status.py
xena/models/recording_scheduling_status.py
xena/pages/email_templates_page.py
xena/pages/jobs_page.py
xena/pages/ouija_board_page.py
xena/pages/page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_email_templates.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py

Tests updated to incorporate a slew of app changes.

Adapt existing scripts to changed behavior

---

diablo/api/status_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-394

DIABLO-394, CanvasException during /api/ping should not cause Diablo error alert email

---

diablo/sql_templates/update_rds_sis_sections.template.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-387

DIABLO-387 Null out those phantom instructors

---

config/default.py
config/test.py
diablo/api/course_controller.py
diablo/api/util.py
diablo/lib/interpolator.py
package-lock.json
package.json
src/api/course.ts
src/main.ts
src/views/Ouija.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-152
Example of download filename: `courses-queued_for_scheduling-2208_2020-06-09_09-19-50.csv`

DIABLO-152, /ouija offers 'Download CSV'

---

src/components/course/CoursesDataTable.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-242

DIABLO-242 Don't display counts for invisible courses

---

diablo/api/course_controller.py
fixtures/calnet/user_for_uid_10004.json
fixtures/calnet/user_for_uid_10005.json
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-152

DIABLO-152, instructor name/email column added to /ouija CSV download

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-382

DIABLO-382, schedules in Kaltura are tagged with 'ets_course_capture'

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-401

DIABLO-401, the are-you-sure dialog includes 'Kaltura series will be deleted'

---

diablo/jobs/kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-400

DIABLO-400 Don't blow up if the course for an approval has gone away

---

.ebextensions/00_ami.config

DIABLO-399, AWS security-groups per env variables, in EB console

---

diablo/api/course_controller.py
src/components/course/CoursePageSidebar.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-402

DIABLO-402 Allow queued courses to be unscheduled

---

.ebextensions/00_ami.config

DIABLO-399, put quotes on SECURITY_GROUP env var references

---

xena/fixtures/test-courses.json
xena/pages/sign_up_page.py
xena/tests/test_unschedule.py

Also cleans up the test-courses.json fixture.

Tests for unscheduling

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-398

DIABLO-398 Screen those pesky TAs out of one more subquery

---

src/components/job/DisableJobToggle.vue
src/components/job/JobHistory.vue
src/main.ts
src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-324

DIABLO-324, intuitive enable/disable on /jobs; break off components

---

src/components/course/CoursesDataTable.vue
src/views/CourseChanges.vue
src/views/Ouija.vue
src/views/User.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-340
Course link, instructor approval checkmark.

DIABLO-340 Improvements to Course Changes page

---

src/mixins/Utils.vue
src/views/email/EditEmailTemplate.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-365

DIABLO-365, disable 'Save' if required input is blank

---

xena/pages/diablo_pages.py
xena/pages/jobs_page.py
xena/pages/ouija_board_page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_x_listings.py

The cross-listed courses that drive the test are in the local test-courses file ... of course.

Initial cross-listings tests

---

diablo/api/email_controller.py
diablo/externals/b_connected.py
diablo/jobs/admin_emails_job.py
diablo/jobs/queued_emails_job.py
diablo/merged/emailer.py
diablo/models/development_db.py
diablo/models/sent_email.py
diablo/models/sis_section.py
scripts/db/migrate/2020/20200610-DIABLO-345/alter_recipient_uid.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
tests/test_jobs/test_invitation_job.py
tests/test_jobs/test_kaltura_job.py
tests/test_jobs/test_queued_emails_job.py
xena/test_utils/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-345

DIABLO-345 Unwrap single-element email recipients array

---

diablo/models/sis_section.py
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-405

DIABLO-405, /room page: sort courses by meeting_days, meeting_start_time

---

diablo/jobs/util.py
diablo/models/sis_section.py
scripts/db/migrate/2020/20200611-DIABLO-406/add_section_principal_listing.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-406

DIABLO-406 Adjust data model for cross-listings

---

.ebextensions/00_ami.config

[release] DIABLO-399, prod security-groups in 00_ami.config

---

src/views/Ouija.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-397
Remove a bit of extraneous code with hope that the bug will manifest differently.

DIABLO-397, Race condition in /ouija? Remove 'catch' to rule out legit error

---

diablo/api/job_controller.py
diablo/jobs/base_job.py
tests/test_api/test_job_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-364

DIABLO-364, /jobs page kicks off job thread and does not wait for finish

---

.ebextensions/00_ami.config
scripts/codebuild/assign-security-groups.sh

[release branch PR](https://github.com/ets-berkeley-edu/diablo/pull/284) already merged

DIABLO-399, security-groups on release branch; test shell script on benign entries in 00_ami.config

---

.ebextensions/00_ami.config

After CodePipeline deploy I will verify that, in prod and non-prod builds, our script is swapping in proper values.

DIABLO-399, non-prod security-groups

---

.ebextensions/00_ami.config

[release] DIABLO-399, restore env vars in 00_ami.config; the replace-token script verified in previous PR

---

package.json
src/views/BaseView.vue
src/views/Login.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-417

DIABLO-417, as part of Vuetify rollback: v-main -> v-content

---

diablo/externals/calnet.py
diablo/merged/calnet.py
fixtures/calnet/user_for_uid_10000.json
fixtures/calnet/user_for_uid_10001.json
fixtures/calnet/user_for_uid_10002.json
fixtures/calnet/user_for_uid_10003.json
fixtures/calnet/user_for_uid_10004.json
fixtures/calnet/user_for_uid_10005.json
fixtures/calnet/user_for_uid_10006.json
fixtures/calnet/user_for_uid_10007.json
fixtures/calnet/user_for_uid_10008.json
fixtures/calnet/user_for_uid_10009.json
fixtures/calnet/user_for_uid_10010.json
fixtures/calnet/user_for_uid_90001.json

https://jira.ets.berkeley.edu/jira/browse/DIABLO-422
https://jira.ets.berkeley.edu/jira/browse/DIABLO-420
Deprecated attributes: https://calnetweb.berkeley.edu/calnet-technologists/ldap-directory-service/ldap-simplification-and-standardization

DIABLO-422, discard unused and deprecated LDAP attributes (eg, berkeleyEduUnitCalNetDeptName)

---

config/test.py
diablo/api/config_controller.py
diablo/externals/b_connected.py
diablo/lib/util.py
diablo/merged/emailer.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-425

DIABLO-425, non-prod emails: prefix subject line with environment info

---

tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-425
This was supposed to be in my previous PR.

DIABLO-425, minor test coverage: email subject line per env

---

diablo/models/approval.py
src/views/Course.vue
xena/models/publish_type.py
xena/pages/sign_up_page.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-427

DIABLO-427, sign-up text change per Kaltura moderation limitation

---

src/views/CourseChanges.vue
xena/pages/course_changes_page.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-410

DIABLO-410, accurate messaging on /changes page

---

src/views/BaseView.vue
xena/pages/diablo_pages.py
xena/pages/page.py
xena/test_utils/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-323
@pfarestveit should have a look.
* I replaced use of `from config import xena` with `app.config['FOO']`
* I removed the log_out retry. I ran tests locally and Xena seemed to have success. Hopefully, due to changes in menu (Vue) code.

DIABLO-323, Xena needs to rely on logout link, no retry necessary

---

diablo/api/course_controller.py
diablo/jobs/util.py
diablo/lib/interpolator.py
diablo/models/sis_section.py
diablo/models/user.py
src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Home.vue
src/views/room/PrintableRoom.vue
tests/test_api/api_test_utils.py
tests/test_api/test_course_controller.py
tests/test_api/test_room_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-421
I expect this to inaugurate an era of chaos and confusion in Diablo, but we may as well jump in. The idea is to surface multiple meeting patterns where they exist, but not get in the way of business as usual for more typically scheduled courses. We'll have to sort out UX and workflows as we go.

DIABLO-421 Rework course feed generation for multiple meeting patterns

---

src/views/BaseView.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-323
Reverting a small bit of what was done in yesterday's PR #301 (side-nav markup)

DIABLO-323, fix herky-jerky side nav

---

src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-421
Follow-up to #302. No thanks to you, Vue linter!

DIABLO-421 Fix typo

---

config/default.py
diablo/api/config_controller.py
diablo/jobs/sis_data_refresh_job.py
diablo/lib/development_db_utils.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-426
Less code, more data.

DIABLO-426, load mock (pilot) course data immediately after sis_data_refresh

---

src/components/course/CoursesDataTable.vue
src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-437

DIABLO-437, instructor home handles course with multiple meeting locations

---

diablo/models/sis_section.py
src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/views/BaseView.vue
src/views/Home.vue
src/views/room/Room.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-437
* `course-data-table` plays nice with multiple meetings
* show meeting dates if `meetingDateRangesVary`

DIABLO-437, /course page when meeting dates vary

---

.eslintrc.js
package-lock.json
package.json
src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/components/course/ToggleOptOut.vue
src/components/room/SelectRoomCapability.vue
src/views/BaseView.vue
src/views/Jobs.vue
src/views/Ouija.vue
src/views/User.vue
src/views/email/EditEmailTemplate.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-437
UI fix in sidebar, for instructors.

DIABLO-437, multi-meetings UI fix; added eslintrc rules

---

config/xena.py
xena/conftest.py
xena/models/canvas_site.py
xena/models/publish_type.py
xena/models/section.py
xena/pages/canvas_page.py
xena/pages/diablo_pages.py
xena/pages/jobs_page.py
xena/pages/kaltura_page.py
xena/pages/page.py
xena/test_utils/util.py
xena/tests/test_course_changes.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_x_listings.py

To Do:
- Debug tests when QAT is back online
- Do the TODOs

Xena learns to make course sites like Teena

---

src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-447

DIABLO-447, UI fix: no border if 2+ meetings

---

diablo/api/auth_controller.py
src/main.ts
src/views/BaseView.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-198
https://jira.ets.berkeley.edu/jira/browse/DIABLO-448

DIABLO-198, redirect to /login page if session expires

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-397
See stacktrace in Jira.

DIABLO-397, tolerate None start/end time

---

diablo/jobs/instructor_emails_job.py
src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-449

DIABLO-449, instructor_emails_job must play by rules of dual/hybrid meetings

---

src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-435

DIABLO-435 Pretty formatting for course dates

---

diablo/jobs/invitation_job.py
tests/test_jobs/test_invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-442

DIABLO-442 Invitations only when exactly one eligible meeting

---

diablo/lib/interpolator.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-454

DIABLO-454, in email interpolator, meetings can be None

---

diablo/jobs/admin_emails_job.py
diablo/models/email_template.py
scripts/db/migrate/2020/20200623-DIABLO-443/alter_email_template_type_enum.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-443

DIABLO-443, add email-template-type: admin_alert_multiple_meeting_patterns

---

diablo/api/course_controller.py
diablo/api/util.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-434

DIABLO-434 Separate ouija filter for scheduled-with-nonstandard-dates

---

diablo/jobs/kaltura_job.py
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-445

DIABLO-445 No automated approval or scheduling for multiple-meeting courses

---

diablo/jobs/admin_emails_job.py
diablo/lib/interpolator.py
diablo/models/development_db.py
diablo/models/email_template.py
fixtures/sis/courses.json
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/test_jobs/test_invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-443
I altered test data such that "PHYSICS 7A LEC 001 (dual mode instruction)" is meeting in one eligible room, one ineligible, and online.

DIABLO-443, admin_alert_multiple_meeting_patterns email if 'funky dates' scheduled

---

diablo/jobs/admin_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-443
Give the 'queued' their due respect.

DIABLO-443, no admin alert email if already sent or queued

---

diablo/jobs/admin_emails_job.py
diablo/jobs/util.py
diablo/models/development_db.py
diablo/models/scheduled.py
diablo/models/sis_section.py
diablo/sql_templates/update_rds_sis_sections.template.sql
scripts/db/migrate/2020/20200624-DIABLO-456/column_type_timestamp_for_meeting_dates.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
tests/test_jobs/test_email_alerts_for_admins.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-456
Please review/merge this PR before master PR #332. 
Once I have verified schema change in diablo-qa env then I'll do the same in dev.

[QA] DIABLO-456, meeting dates in sis_sections and scheduled are now timestamps

---

src/components/course/CoursePageSidebar.vue
src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-457

DIABLO-457, approve course and meeting info remains

---

diablo/jobs/base_job.py
diablo/jobs/instructor_emails_job.py
diablo/jobs/util.py
diablo/models/queued_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-460

DIABLO-460, formatted stacktrace in error emails

---

diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-459
The Jira above has lots o' details.

DIABLO-459, use Kaltura category_entry to find Canvas course sites mapped to schedule

---

diablo/api/auth_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-198

DIABLO-198, in CAS callback, log redirect_path for debugging

---

diablo/api/auth_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-198
Removed unused `casLogin` marker and other fluff.

DIABLO-198, bit more cleanup in /cas/callback

---

diablo/api/course_controller.py
diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-461

DIABLO-461 Include home-cooked meetingType in CSV download

---

diablo/externals/canvas.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-430
See latest stack-trace in Jira above.

DIABLO-430, not every 'section' from Canvas API has sis_section_id attr

---

diablo/jobs/background_job_manager.py
diablo/jobs/base_job.py
run.py
scripts/db/drop_schema.sql
scripts/db/migrate/2020/20200625-DIABLO-458/create_job_runner_table.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-458

DIABLO-458 One instance at a time running jobs, please

---

run.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-458
Ordering follow-up to #344.

DIABLO-458 Set EC2_INSTANCE_ID before app created

---

diablo/externals/kaltura.py
diablo/lib/kaltura_util.py
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-386
As a parent, I was relieved to discover I can 'cancel' children. (API disallows 'delete' of children.)

DIABLO-386, enhance the creation of blackout-dates; 'cancel' children if they have blackout-conflict

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-467

DIABLO-467, invite 'Send Invite' to the party

---

diablo/api/course_controller.py
diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py
diablo/lib/berkeley.py
diablo/lib/kaltura_util.py
scripts/commands.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-470
https://jira.ets.berkeley.edu/jira/browse/DIABLO-469

DIABLO-470, if unschedule series then only cancel/delete future events

---

diablo/models/sis_section.py
src/components/course/CoursePageSidebar.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-464

DIABLO-464, if last-recording != meeting-end-date then say so on /course

---

diablo/models/approval.py
diablo/models/scheduled.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-466

DIABLO-466 Make the spirits respond faster

---

src/views/CourseChanges.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-465

DIABLO-465, use meeting.recordingEndDate when display diff on course-changes page

---

diablo/api/user_controller.py
src/api/user.ts
src/router.ts
src/views/Attic.vue
src/views/BaseView.vue
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-472
Don't go in The Attic!

DIABLO-472, simple page lists all admin users and configs of interest

---

src/views/Attic.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-472
This minor cleanup was late for the last PR.

DIABLO-472, tidy the Attic a bit more

---

diablo/jobs/instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-473

DIABLO-473 Lock up that KeyError

---

config/default.py
diablo/externals/canvas.py
diablo/lib/util.py
diablo/xml_templates/media_gallery.xml
diablo/xml_templates/my_media.xml
diablo/xml_templates/quick_ingest.xml
diablo/xml_templates/video_submission.xml
scripts/commands.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-409

DIABLO-409 Kaltura LTI repointing script

---

diablo/externals/kaltura.py
src/components/kaltura/KalturaEventList.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-474

DIABLO-474, restore kaltura events.to_api_json with option for raw-resultset

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-405

DIABLO-405 Teach Pazuzu about weekdays

---

diablo/api/job_controller.py
diablo/models/job_history.py
src/api/job.ts
src/views/Jobs.vue
tests/test_api/test_job_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-475

DIABLO-475, remove day_count param from /job/history API

---

src/components/course/ScheduledCourse.vue
src/components/kaltura/KalturaEventList.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-476

DIABLO-476, remove 'raw JSON' option from /room and /course pages

---

scripts/commands.py

NOJIRA, fix method arg ref in delete-events script

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-480

DIABLO-480, simple name for kaltura_base_entry

---

diablo/jobs/admin_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-484

DIABLO-484 One more KeyError on the big brass ring

---

diablo/lib/kaltura_util.py
src/components/kaltura/KalturaEventList.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-486
So we can verify that events on blackout dates are "Cancelled"

DIABLO-486, add status column to 'Kaltura > Series' on /room page

---

diablo/jobs/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-485

DIABLO-485 Exclude non-room locations from xlist calculation

---

diablo/api/course_controller.py
src/api/course.ts
src/components/attic/Configs.vue
src/mixins/Utils.vue
src/views/Attic.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-488
Arbitrary stats can live in this new section of `/attic`.

DIABLO-488, add 'Total scheduled count' to the /attic page

---

config/xena.py
xena/models/email_template_type.py
xena/models/meeting.py
xena/models/term.py
xena/pages/canvas_page.py
xena/pages/course_changes_page.py
xena/pages/kaltura_page.py
xena/pages/ouija_board_page.py
xena/pages/room_page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py
xena/tests/test_enable_rooms.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py

Get the test suite working again in light of recent functional changes, and break up the course changes test script into three.

More Xena tests fixes

---

diablo/jobs/instructor_emails_job.py
diablo/models/development_db.py
tests/test_api/api_test_utils.py
tests/test_api/test_course_controller.py
tests/test_jobs/test_admin_emails_job.py
tests/test_jobs/test_instructor_emails_job.py
tests/test_models/test_queued_email.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-497

DIABLO-497, no repeat 'room_change' alerts to instructors, with test coverage

---

diablo/api/email_controller.py
diablo/lib/interpolator.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-498

DIABLO-498, the test_email feature should exercise all template_codes, prefers eligible course

---

diablo/jobs/instructor_emails_job.py
diablo/jobs/invitation_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-499

DIABLO-499, fix descriptions of invitation_job and instructor_emails_job

---

diablo/jobs/instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-497
* If no email template is available we want to know asap. 
* The `Scheduled.add_alert` line was in the `for instructor in course` loop, causing dupes.
* You'll get simpler diff with `?w=1`

DIABLO-497, fail immediately if no email template; no dupe scheduled.alerts

---

diablo/models/scheduled.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-497

DIABLO-497, postgres + arrays + SQLAlchemy is a wicked stew

---

diablo/lib/interpolator.py
tests/test_api/test_email_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-503

DIABLO-503, fix and test coverage for /api/email/template/codes

---

src/components/room/SelectRoomCapability.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-335

DIABLO-335, non-auditorium can have screencast_and_video

---

diablo/api/job_controller.py
diablo/models/job.py
src/views/Jobs.vue
tests/test_api/test_job_controller.py
tests/test_jobs/test_admin_emails_job.py
tests/test_jobs/test_instructor_emails_job.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-501
This rule will simplify any bug fix necessary for DIABLO-501

DIABLO-501, you cannot edit job schedule if job is enabled or running

---

diablo/api/job_controller.py
diablo/jobs/background_job_manager.py
tests/test_jobs/test_background_job_manager.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-501
A restart that works.

DIABLO-501, job_manager.restart() uses schedule.clear

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-505

DIABLO-505, proper CSS for alerts on /course

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-507

DIABLO-507, weird schedules: no send-invite button for type D

---

src/views/CourseChanges.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-511

DIABLO-511, do not tag schedule changes as 'ineligible'

---

xena/models/async_job.py
xena/models/meeting.py
xena/pages/course_changes_page.py
xena/pages/jobs_page.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py
xena/tests/test_unschedule.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py
xena/tests/test_weird_type_d.py
xena/tests/test_x_listings.py

Some of the course changes expectations will need updating when bugs are resolved.

Tests for weird schedules

---

diablo/externals/kaltura.py
src/components/course/ScheduledCourse.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-513
https://jira.ets.berkeley.edu/jira/browse/DIABLO-516
Instead of...
...we get...

DIABLO-516 / DIABLO-513, tidy up admin-alerts on /course; and Kaltura API 'until' arg is end-time of last recording

---

src/components/course/CourseRoom.vue
src/components/course/ObsoleteSchedule.vue
src/components/course/ScheduledCourse.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-515

DIABLO-515, if obsolete room then show on /course; CSS fix on /changes

---

src/components/course/ObsoleteSchedule.vue
src/views/CourseChanges.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-520

DIABLO-520, remove old '/changes' UX; only show room on /changes if obsolete

---

xena/pages/course_changes_page.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py

Part 1 updates non-weird course changes.

Update Xena's changes UI

---

src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-522

DIABLO-522, on /room page, only offer printable if courses are scheduled in _this_ room

---

diablo/api/user_controller.py
src/api/user.ts
src/components/course/Instructor.vue
src/components/course/ObsoleteSchedule.vue
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-523

DIABLO-523, /changes page has two kinds of obsolete instructor

---

src/components/course/CoursesDataTable.vue
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-524
Plus, clean-up.

DIABLO-524, sort by 'room.location' with multiple meetings in mind

---

diablo/api/config_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-494

DIABLO-494 Enhance API version feed

---

src/components/course/Instructor.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-526

DIABLO-526, show 'invite not sent' icon if and only if course is eligible

---

src/components/util/PageTitle.vue
src/views/Attic.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Home.vue
src/views/Jobs.vue
src/views/NotFound.vue
src/views/Ouija.vue
src/views/User.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue
src/views/room/Room.vue
src/views/room/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-528

DIABLO-528, PageTitle component for standard header style

---

xena/pages/course_changes_page.py
xena/pages/jobs_page.py
xena/pages/ouija_board_page.py
xena/test_utils/util.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py

Hopefully the changes page is now done-done...

Fix tests for weird course changes

---

diablo/api/user_controller.py
diablo/externals/calnet.py
diablo/jobs/util.py
diablo/merged/calnet.py
diablo/models/user.py
fixtures/calnet/user_for_uid_10000.json
fixtures/calnet/user_for_uid_10001.json
fixtures/calnet/user_for_uid_10002.json
fixtures/calnet/user_for_uid_10003.json
fixtures/calnet/user_for_uid_10004.json
fixtures/calnet/user_for_uid_10005.json
fixtures/calnet/user_for_uid_10006.json
fixtures/calnet/user_for_uid_10007.json
fixtures/calnet/user_for_uid_10008.json
fixtures/calnet/user_for_uid_10009.json
fixtures/calnet/user_for_uid_10010.json
fixtures/calnet/user_for_uid_90001.json
src/views/User.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-517

DIABLO-517, use berkeleyEduAlternateID (CalNet) for user email

---

src/components/util/PageTitle.vue
src/views/BaseView.vue
src/views/Course.vue
src/views/CourseChanges.vue
src/views/Home.vue
src/views/email/EditEmailTemplate.vue
src/views/email/EmailTemplates.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-528
Review with `?w=1`

DIABLO-528, a bit more cleanup in header UI

---

diablo/models/development_db.py
diablo/models/sis_section.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-527

DIABLO-527, /ouija > only eligible courses in 'Invited' filter

---

src/components/course/CoursePageSidebar.vue
src/components/course/CourseRoom.vue
src/components/course/CoursesDataTable.vue
src/components/course/Instructor.vue
src/components/course/ObsoleteSchedule.vue
src/components/email/TemplateCodesDialog.vue
src/components/kaltura/KalturaEventList.vue
src/components/util/PageTitle.vue
src/components/util/TermsAgreementText.vue
src/views/BaseView.vue
src/views/Course.vue
src/views/Ouija.vue
src/views/room/Rooms.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-530
On instructor homepage, icon is only clickable at 16:20.

DIABLO-530, vuetify suggested use of 'attrs' for aria attributes

---

src/mixins/Utils.vue
src/views/BaseView.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-533

DIABLO-533, stripAnchorRef from router-view; fix skip-to-content link

---

public/index.html
src/main.ts

https://jira.ets.berkeley.edu/jira/browse/DIABLO-539

DIABLO-539, @mdi/font is installed, no need for stylesheet URL ref

---

diablo/models/scheduled.py
diablo/models/sis_section.py
src/components/course/CoursePageSidebar.vue
src/components/course/CoursesDataTable.vue
src/components/course/ObsoleteSchedule.vue
src/components/util/Days.vue
src/mixins/Utils.vue
src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-531

DIABLO-531, accessibility fix: days of the week announced as 'moe', 'wee', etc

---

diablo/lib/util.py
src/components/course/CoursePageSidebar.vue
src/components/util/Days.vue
src/components/util/Footer.vue
src/views/room/PrintableRoom.vue
src/views/room/Room.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-535
https://jira.ets.berkeley.edu/jira/browse/DIABLO-536

DIABLO-535 / DIABLO-536, small accessibility improvements; 'None not iterable' fix

---

diablo/lib/util.py
src/components/course/CoursePageSidebar.vue
src/components/course/ScheduledCourse.vue
src/router.ts
src/views/Course.vue
src/views/Home.vue
src/views/NotFound.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-532
https://jira.ets.berkeley.edu/jira/browse/DIABLO-537

DIABLO-532 / DIABLO-537, proper scrollTo in router; disable v-card clickability

---

src/components/course/CoursePageSidebar.vue
src/components/course/ScheduledCourse.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-537
revert a portion of PR #426

DIABLO-537, revert v-card disabled; links are unclickable

---

src/api/kaltura.ts
src/components/course/CanvasCourseSite.vue
src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-545
Knowing what Kaltura knows is useful.

DIABLO-545, Kaltura category id adjacent to Canvas course site info on /course page

---

src/views/room/PrintableRoom.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-546

DIABLO-546, dates on /room/printable

---

src/router.ts

https://jira.ets.berkeley.edu/jira/browse/DIABLO-540

DIABLO-540, check for to.redirect in router.beforeEach, not only before /login

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-480
Garbage in, garbage out.

DIABLO-480, remove 'scheduled by Diablo' from recording title

---

src/router.ts
src/views/BaseView.vue
src/views/Jobs.vue
xena/pages/diablo_pages.py
xena/pages/jobs_page.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-550?filter=15526

DIABLO-550, rebrand 'Jobs' page title cuz it's very, very boring

---

diablo/jobs/admin_emails_job.py
diablo/jobs/instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-552
Use `?w=1` for an easier read.

DIABLO-552, if email template is unavailable then calmly send_system_error_email

---

diablo/api/auth_controller.py
diablo/models/user.py
src/main.ts
src/views/Login.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-553

DIABLO-553, if user is not auth then tell her/him

---

diablo/api/course_controller.py
diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-555
We _do_ get editor/publish info if summary = `{course_label} ({term_name}) in {room.location}`. I'll report bug to Kaltura.

DIABLO-555, Kaltura bug? No editor/publish info when summary = '{course_label} ({term_name})'

---

src/components/course/CoursesDataTable.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-556

DIABLO-556, no more Captain Howdy tricks on Ouija

---

src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-557

DIABLO-557, computed values in /course sidebar: offerSendInvite, offerUnschedule

---

package-lock.json
package.json
src/components/course/CoursePageSidebar.vue
src/components/course/ScheduledCourse.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-537
Review with `?w=1`

DIABLO-537, no v-card on /course page for no unwanted clickable

---

src/assets/styles/diablo-global.css
src/components/util/Days.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-531
CSS 'speak' prop: https://css-tricks.com/almanac/properties/s/speak/

DIABLO-531, sr-only on day names; sr-skip on 'moe' and 'wee'

---

xena/tests/test_user_permissions.py

Add test for non-auth user

---

diablo/api/email_controller.py
src/components/course/CoursePageSidebar.vue
src/views/email/EmailTemplates.vue
tests/test_api/test_email_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-552
And, I have removed a couple unused endpoints.

DIABLO-552, do not offer 'Send Invite' if template not created yet

---

diablo/jobs/util.py
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-510
This line of code is a final validation step prior to scheduling. A similar check is done, further down with stack.

DIABLO-510, instructor_uids.issubset(approved_by_uids) to schedule

---

src/components/util/PageTitle.vue
src/main.ts
src/mixins/Utils.vue
src/router.ts
src/store/modules/context.ts
src/views/Login.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-532
The `vue-router` trick did not work.

DIABLO-532, put focus on page-title when 'loading' becomes false

---

diablo/externals/kaltura.py
diablo/lib/kaltura_util.py
tests/test_lib/test_kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-558

DIABLO-558, a sensible series description in Kaltura

---

diablo/lib/kaltura_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-558

DIABLO-558, @ is not © (recording series metadata in Kaltura)

---

diablo/__init__.py

First step towards a release candidate.

[QA] NOJIRA, Diablo qa branch is v1.0

---

diablo/__init__.py

Feature dev can continue on master.

NOJIRA, Diablo master branch is v1.1

---

scripts/db/migrate/2020/20200728-DIABLO-478/set_up_uat_after_sis_data_refresh.sql
src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-383
UAT participant UIDs will be passed to SQL script. All UAT courses will be in Cory 277. The mock course data is in S3, with env config files.

DIABLO-478, SQL script to run prior to three day UAT exercise

---

scripts/db/migrate/2020/20200728-DIABLO-478/set_up_uat_after_sis_data_refresh.sql

https://jira.ets.berkeley.edu/jira/browse/DIABLO-478

DIABLO-478, SQL script to set up UAT must delete unwanted cross_listings

---

diablo/lib/development_db_utils.py
diablo/models/sis_section.py
scripts/db/migrate/2020/20200728-DIABLO-478/set_up_uat_after_sis_data_refresh.sql
src/views/Jobs.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-471
https://jira.ets.berkeley.edu/jira/browse/DIABLO-478
Master PR #462

[QA] DIABLO-471, SQL tweak to non-standard filter: odd start_date is relevant only if scheduled beforehand

---

diablo/lib/development_db_utils.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-383
Delete the real to make way for the mock.

DIABLO-383, if mock course section_id matches existing then delete existing

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-567
master PR is #467

[QA] DIABLO-567, instructors get co-edit and co-publish perms in Kaltura series

---

README.md
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-3621
Use `tox -p` instead of `tox`.

BOAC-3621, recommend 'tox --parallel' in Diablo README

---

diablo/jobs/canvas_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-571
A bad Canvas config (eg, term_id) might not be discovered until the customer complains. Let's avoid that scenario.

DIABLO-571, send admin a warning email if Canvas API call returns zero courses

---

xena/pages/sign_up_page.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py
xena/tests/test_weird_type_d.py

Fix schedule verification tests

---

requirements.txt
tox.ini

https://jira.ets.berkeley.edu/jira/browse/DIABLO-589

DIABLO-589, py package updates

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-586

DIABLO-586, put secondary sections into the Course Capture mix

---

diablo/externals/calnet.py
diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-574
A bit of code cleanup during `ldap-test` verification.

DIABLO-574, clean up externals/kaltura.py; ldap-test verified

---

src/views/BaseView.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-573
(dark mode required)

DIABLO-573, my ever changing moods

---

config/default.py
diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-573
Info on appToken approach: 
https://developer.kaltura.com/api-docs/VPaaS-API-Getting-Started/application-tokens.html

DIABLO-573, Kalture API calls auth with appToken, not raw admin credentials

---

scripts/db/migrate/2020/20201208-DIABLO-595/spring_2021_kaltura_blackout_dates.sh

https://jira.ets.berkeley.edu/jira/browse/DIABLO-597

DIABLO-597, shell script wraps 'assign_kaltura_blackout_dates' operation (Spring 2021)

---

diablo/externals/kaltura.py
diablo/jobs/kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-582
Not all categories are Canvas course sites.

DIABLO-582, Kaltura category to_json uses sensible key for 'name'

---

diablo/api/status_controller.py
tests/test_api/test_routes.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-581

DIABLO-581, always response.status = 200 for /api/ping

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-604

DIABLO-604, course page for cross-listed has unique canvas course sites, no dupes

---

xena/models/section.py
xena/pages/sign_up_page.py
xena/test_utils/util.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py
xena/tests/test_unschedule.py
xena/tests/test_user_permissions.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py
xena/tests/test_weird_type_d.py
xena/tests/test_x_listings.py

Tests now create their own section data rather than relying on real data in an external file.

Xena makes her own test data

---

package-lock.json
package.json

https://jira.ets.berkeley.edu/jira/browse/DIABLO-606

DIABLO-606, bump axios version (SSRF vulnerability)

---

.travis.yml
requirements.txt
tox.ini

https://jira.ets.berkeley.edu/jira/browse/DIABLO-608
If it's good for BOA (see https://github.com/ets-berkeley-edu/boac/pull/2786) then...

DIABLO-608, no more concurrent jobs in travis.yml; use tox --parallel

---

.eslintrc.js
src/auth.ts
src/components/attic/Configs.vue
src/main.ts
src/mixins/Utils.vue
src/router.ts
src/store/modules/context.ts
src/views/BaseView.vue
src/views/Login.vue
src/views/email/EditEmailTemplate.vue

NOJIRA, proper eslint rule syntax for 'bracket-spacing'

---

requirements.txt
tox.ini

https://jira.ets.berkeley.edu/jira/browse/DIABLO-615

DIABLO-615, py updates for Diablo

---

diablo/externals/b_connected.py
tests/test_jobs/test_queued_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-624
cc: @pauline2k

DIABLO-624, skip nil and empty email addresses when bconnected.send

---

config/default.py

NOJIRA, wake up Travis with updated easter_egg vid

---

diablo/api/blackout_controller.py
diablo/api/email_controller.py
diablo/lib/util.py
diablo/models/blackout.py
diablo/models/development_db.py
diablo/routes.py
scripts/db/drop_schema.sql
scripts/db/migrate/2021/20210526-DIABLO-614/create_blackouts_table.sql
scripts/db/schema.sql
tests/test_api/test_blackout_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-620
https://jira.ets.berkeley.edu/jira/browse/DIABLO-621
Like the NYC blackout of '77.

DIABLO-620, 'blackouts' schema with model, controller, and tests

---

src/api/blackout.ts
src/router.ts
src/views/BaseView.vue
src/views/blackout/Blackouts.vue
src/views/blackout/EditBlackout.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-622
Aww, crud!

DIABLO-622, front-end views to CRUD da blackouts

---

diablo/externals/kaltura.py
diablo/jobs/blackouts_job.py
requirements.txt
src/views/blackout/Blackouts.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-628
We have not exercised this delete-event-within-series code. I learned that you must "cancel" such event instances, delete is not supported.

DIABLO-628, events of type 'recurrence' must be cancelled, not deleted

---

diablo/externals/kaltura.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-614

DIABLO-614, Three scenarios when invoking Kaltura API: delete

---

diablo/externals/b_connected.py
diablo/lib/util.py
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-629

DIABLO-629, scrub KS session key out of email subject/message

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-631

DIABLO-631, do not describe premium service if premium cost is -zsh

---

config/xena.py
xena/conftest.py
xena/models/async_job.py
xena/models/meeting.py
xena/pages/blackouts_page.py
xena/pages/canvas_page.py
xena/pages/diablo_pages.py
xena/pages/email_page.py
xena/pages/jobs_page.py
xena/pages/page.py
xena/pages/rooms_page.py
xena/test_utils/util.py
xena/test_utils/webdriver_manager.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py

It's lost its shine, so dump it for Firefox.

Put a blackout on Chrome

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-631
The master PR is #518

[QA] DIABLO-631, do not describe premium service if premium cost is -zsh

---

xena/pages/diablo_pages.py
xena/pages/ouija_board_page.py
xena/pages/sign_up_page.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_user_permissions.py
xena/tests/test_x_listings.py

Final Xena fixes for v1.2

---

diablo/jobs/blackouts_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-626

DIABLO-626, delete past blackout_dates per utc_now

---

diablo/api/errors.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/DIABLO-633

DIABLO-633, upgrade to flake8 3.9.2 and fix lint-py errors

---

config/default.py
config/test.py
diablo/models/sis_section.py
requirements.txt
tests/conftest.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-634
Release instructions updated.

DIABLO-634, SQLAlchemy 1.4.20 with necessary corrections

---

config/default.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-631
Course Capture video (w/ operator) cost reduced to $1000.
Release instructions updated.

DIABLO-631, Everything must go! 50% off Course Capture premium

---

requirements.txt

https://jira.ets.berkeley.edu/jira/browse/DIABLO-635
See dupe method args in Kaltura code: https://github.com/kaltura/KalturaGeneratedAPIClientsPython/blob/17.5.0/KalturaClient/Plugins/Reach.py#L2564

DIABLO-635, KalturaApiClient v17.5.0 has a bug; revert to 17.2.0

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config
.travis.yml
README.md
buildspec.yml
requirements.txt
scripts/get_config_file_from_s3.sh
tests/conftest.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-649
DO NOT MERGE (yet). I want to verify Travis build on Python 3.8 and I need a little time to set up CodeBuild/Pipeline.

DIABLO-649, upgrade to Linux 2 (Python 3.8): ami.config, py deps, and .travis

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/DIABLO-649
revert mistaken merge (PR #528)

DIABLO-649, revert accidental change to Diablo master

---

diablo/api/auth_controller.py
diablo/api/errors.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-655
And some debug logging for good measure.

[QA] DIABLO-655, remove @cache annotation on  def cas_login_url()

---

diablo/api/auth_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-655

DIABLO-655, remove verbose logging intended only for v1.2.1 patch

---

diablo/__init__.py
diablo/merged/calnet.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-653

DIABLO-653, increase get_calnet_user_for_uid cache timeout to 24 hours

---

diablo/__init__.py
diablo/merged/calnet.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-653
master PR is #536

[QA] DIABLO-653, increase get_calnet_user_for_uid cache timeout to 24 hours

---

diablo/lib/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-658
https://jira.ets.berkeley.edu/jira/browse/DIABLO-657

[QA] DIABLO-658, fix 'failed parsing meeting[days]'; do not iterate None

---

diablo/lib/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-658
https://jira.ets.berkeley.edu/jira/browse/DIABLO-657
QA PR is #538

DIABLO-658, fix 'failed parsing meeting[days]'; do not iterate None

---

diablo/lib/berkeley.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-659
The quest for None-safe code. We want to tread lightly as not to disrupt standard workflows.

[QA] DIABLO-659, no BOOM! when scheduled course has dates changed to 'None'

---

diablo/lib/berkeley.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-659
QA PR is #541

DIABLO-659, no BOOM! when scheduled course has dates changed to 'None'

---

diablo/jobs/kaltura_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-660
Review with `?w=1`

DIABLO-660, log 'no event in Kaltura' only when statement is true

---

diablo/lib/berkeley.py
diablo/lib/util.py
diablo/models/approval.py
diablo/models/sis_section.py
src/components/course/CoursesDataTable.vue
src/components/course/ScheduledCourse.vue
src/components/util/CalNetProfile.vue
src/components/util/CreateBlackoutDialog.vue
src/views/Course.vue
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-656
https://jira.ets.berkeley.edu/jira/browse/DIABLO-661
Includes fix for null-safe date formatting.

DIABLO-656, lazy-load CalNet profile on client-side to speed up page-load time

---

config/xena.py
xena/models/meeting.py
xena/test_utils/util.py
xena/tests/test_course_changes_instructor.py
xena/tests/test_course_changes_room.py
xena/tests/test_course_changes_schedule.py
xena/tests/test_email_templates.py
xena/tests/test_invitations.py
xena/tests/test_sign_up_0.py
xena/tests/test_sign_up_1.py
xena/tests/test_sign_up_2.py
xena/tests/test_sign_up_3.py
xena/tests/test_weird_type_b.py
xena/tests/test_weird_type_c.py
xena/tests/test_weird_type_d.py
xena/tests/test_x_listings.py

Some test coverage for unpleasant SIS data.  Also, Yahoo suspects Xena isn't real (as if), so adds option to skip email testing.

Xena has null to fear but null itself

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-664

[QA] DIABLO-664 Restrict cross-listing instructor query to Diablo-relevant roles

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-664
Master-branch version of #548.

DIABLO-664 Restrict cross-listing instructor query to Diablo-relevant roles

---

diablo/api/auth_controller.py
src/components/course/CoursePageSidebar.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-663
Diablo is in the details, not the UI.

DIABLO-663, customers should never see the word 'Diablo'

---

diablo/lib/util.py
diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-666
666 is a wicked bug.

[QA] DIABLO-666, safe date parsing on recording start and end dates

---

diablo/models/sis_section.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-666
This change was included in patch PR #552

DIABLO-666, safe_strftime when meeting dates to_api_json

---

src/components/util/CalNetProfile.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-662

DIABLO-662, use CalNetProfile component to render list of approvedBy

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-668

DIABLO-668, disallow scheduling if course has invalid times/dates

---

diablo/jobs/instructor_emails_job.py
diablo/models/room.py
tests/test_jobs/test_instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-671
No QA PR necessary.

DIABLO-671, do not send room_change_no_longer_eligible if course moves to eligible room

---

diablo/jobs/instructor_emails_job.py
tests/test_jobs/test_instructor_emails_job.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-671
Previous PR did not have the 'new room not eligible' condition. Expanded the test coverage, too.

DIABLO-671, room_change email if (1) new room not eligible, or (2) scheduled room no longer eligible

---

diablo/api/user_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-674

DIABLO-674, instructors have permission to see CalNet details of other

---

src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-676

DIABLO-676, sign-up confirmation: what a diff a little padding makes

---

package-lock.json
package.json
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/DIABLO-647

DIABLO-647, upgrade Diablo dependencies, including 'vulnerable' axios

---

diablo/models/approval.py
diablo/models/room.py
scripts/db/migrate/2021/20211001-DIABLO-672/add_value_to_recording_type_enum.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
tests/test_api/test_room_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-672
Release instructions updated.

DIABLO-672, recording_types db enum get presenter_presentation_audio_with_operator

---

diablo/api/course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-673
CSVs are what we do.

DIABLO-673, full section display name in csv download

---

package-lock.json
package.json
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/DIABLO-684

DIABLO-684, minor package updates (eg, axios)

---

diablo/jobs/util.py
diablo/lib/development_db_utils.py
diablo/models/sis_section.py
diablo/sql_templates/update_rds_sis_sections.template.sql
fixtures/sis/courses.json
scripts/db/migrate/2021/20211004-DIABLO-678/sis_sections_soft_delete.sql
scripts/db/schema.sql
tests/test_api/test_course_controller.py
xena/test_utils/util.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-678
For admin users, deleted courses will surface on `/changes` view and course overview page.
Release instructions updated.

DIABLO-678, 'sis_sections' table gets deleted_at; sis_import job does the right thing

---

diablo/api/course_controller.py
diablo/models/sis_section.py
fixtures/sis/courses.json
src/assets/styles/diablo-global.css
src/components/course/CoursePageSidebar.vue
src/components/util/PageTitle.vue
src/views/Course.vue
tests/test_api/api_test_utils.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/DIABLO-678
And, any user (admin or instructor) can view `/course` page of deleted section and yet the page is stripped of all powers.

DIABLO-678, if previously scheduled, cancelled sections show up in certain filters

---

src/components/course/ObsoleteSchedule.vue

https://jira.ets.berkeley.edu/jira/browse/DIABLO-679

DIABLO-679, UI tidying on /changes page for cancelled sections
